import { Add, Delete, DragIndicator } from '@mui/icons-material'
import {
  Box,
  Button,
  Checkbox,
  FormControl,
  FormControlLabel,
  Grid,
  IconButton,
  InputLabel,
  MenuItem,
  Paper,
  Select,
  Stack,
  TextField,
  Tooltip,
  Typography,
} from '@mui/material'
import {
  DndContext,
  KeyboardSensor,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
  type DragEndEvent,
} from '@dnd-kit/core'
import {
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import type { Dispatch, SetStateAction } from 'react'
import type { FieldType } from '../types'
import { newBuilderField, reorderBuilderFields, type BuilderField } from '../utils/builderField'
import { isAutoGeneratedFieldId, labelToFieldKey } from '../utils/fieldKey'
import { RelationFieldSettings } from './RelationFieldSettings'

const fieldTypes: FieldType[] = [
  'input',
  'textarea',
  'number',
  'datepicker',
  'profile_upload',
  'select',
  'relation',
]

interface SectionFieldsEditorProps {
  fields: BuilderField[]
  setFields: Dispatch<SetStateAction<BuilderField[]>>
  sectionName: string
}

interface SortableFieldCardProps {
  field: BuilderField
  index: number
  sectionName: string
  canDelete: boolean
  onUpdate: (clientId: string, patch: Partial<BuilderField>) => void
  onDelete: (clientId: string) => void
}

function SortableFieldCard({
  field,
  index,
  sectionName,
  canDelete,
  onUpdate,
  onDelete,
}: SortableFieldCardProps) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: field.clientId,
  })

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.85 : 1,
  }

  const title = field.label.trim() || field.id || `Field ${index + 1}`

  return (
    <Paper ref={setNodeRef} style={style} variant="outlined" sx={{ p: 2 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, mb: 1.5 }}>
        <Tooltip title="Drag to reorder fields">
          <IconButton
            size="small"
            aria-label={`Reorder ${title}`}
            sx={{ cursor: isDragging ? 'grabbing' : 'grab', p: 0.25 }}
            {...attributes}
            {...listeners}
          >
            <DragIndicator fontSize="small" />
          </IconButton>
        </Tooltip>
        <Typography variant="subtitle2" sx={{ flex: 1 }}>
          {title}
          <Typography component="span" variant="caption" color="text.secondary" sx={{ ml: 1 }}>
            #{index + 1}
          </Typography>
        </Typography>
        <IconButton
          color="error"
          size="small"
          onClick={() => onDelete(field.clientId)}
          disabled={!canDelete}
          aria-label={`Delete ${title}`}
        >
          <Delete fontSize="small" />
        </IconButton>
      </Box>

      <Grid container spacing={2}>
        <Grid size={{ xs: 12, md: 3 }}>
          <TextField
            fullWidth
            label="Field Label"
            value={field.label}
            onChange={(event) => onUpdate(field.clientId, { label: event.target.value })}
            required
          />
        </Grid>
        <Grid size={{ xs: 12, md: 3 }}>
          <TextField
            fullWidth
            label="Field key"
            value={field.id}
            onChange={(event) =>
              onUpdate(field.clientId, {
                id: event.target.value.replace(/\s/g, ''),
              })
            }
            required
            helperText="Data key (auto from label)"
            placeholder="e.g. roleName"
          />
        </Grid>
        <Grid size={{ xs: 12, md: 2 }}>
          <TextField
            fullWidth
            label="Grid (1-12)"
            type="number"
            value={field.grid}
            onChange={(event) => onUpdate(field.clientId, { grid: Number(event.target.value) })}
            required
          />
        </Grid>
        <Grid size={{ xs: 12, md: 4 }}>
          <FormControl fullWidth>
            <InputLabel>Choose Field</InputLabel>
            <Select
              value={field.type}
              label="Choose Field"
              onChange={(event) =>
                onUpdate(field.clientId, { type: event.target.value as FieldType })
              }
            >
              {fieldTypes.map((type) => (
                <MenuItem key={type} value={type}>
                  {type}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        </Grid>
        <Grid size={{ xs: 12, md: 2 }}>
          <FormControlLabel
            control={
              <Checkbox
                checked={field.required}
                onChange={(event) => onUpdate(field.clientId, { required: event.target.checked })}
              />
            }
            label="Required"
          />
        </Grid>

        {field.type === 'number' && (
          <>
            <Grid size={{ xs: 12, md: 3 }}>
              <TextField
                fullWidth
                label="Min"
                type="number"
                value={field.min ?? ''}
                onChange={(event) => onUpdate(field.clientId, { min: Number(event.target.value) })}
              />
            </Grid>
            <Grid size={{ xs: 12, md: 3 }}>
              <TextField
                fullWidth
                label="Max"
                type="number"
                value={field.max ?? ''}
                onChange={(event) => onUpdate(field.clientId, { max: Number(event.target.value) })}
              />
            </Grid>
          </>
        )}

        {field.type === 'datepicker' && (
          <>
            <Grid size={{ xs: 12, md: 3 }}>
              <TextField
                fullWidth
                type="date"
                value={field.minDate ?? ''}
                onChange={(event) => onUpdate(field.clientId, { minDate: event.target.value })}
                helperText="Min Date"
                slotProps={{ inputLabel: { shrink: true } }}
              />
            </Grid>
            <Grid size={{ xs: 12, md: 3 }}>
              <TextField
                fullWidth
                type="date"
                value={field.maxDate ?? ''}
                onChange={(event) => onUpdate(field.clientId, { maxDate: event.target.value })}
                helperText="Max Date"
                slotProps={{ inputLabel: { shrink: true } }}
              />
            </Grid>
          </>
        )}

        {field.type === 'select' && (
          <Grid size={{ xs: 12 }}>
            <TextField
              fullWidth
              label="Dropdown Options (comma separated)"
              value={(field.options ?? []).join(',')}
              onChange={(event) =>
                onUpdate(field.clientId, {
                  options: event.target.value
                    .split(',')
                    .map((value) => value.trim())
                    .filter(Boolean),
                })
              }
            />
          </Grid>
        )}

        {field.type === 'relation' && (
          <RelationFieldSettings
            field={field}
            currentSectionName={sectionName}
            onChange={(patch) => onUpdate(field.clientId, patch)}
          />
        )}
      </Grid>
    </Paper>
  )
}

export function SectionFieldsEditor({ fields, setFields, sectionName }: SectionFieldsEditorProps) {
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 6 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }),
  )

  const updateField = (clientId: string, patch: Partial<BuilderField>) => {
    setFields((prev) =>
      prev.map((field) => {
        if (field.clientId !== clientId) return field
        const next = { ...field, ...patch }
        if (patch.label != null && patch.id === undefined && isAutoGeneratedFieldId(field.id)) {
          const key = labelToFieldKey(patch.label)
          if (key) next.id = key
        }
        return next
      }),
    )
  }

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event
    if (!over || active.id === over.id) return
    setFields((prev) => reorderBuilderFields(prev, String(active.id), String(over.id)))
  }

  const sortableIds = fields.map((field) => field.clientId)

  return (
    <Box>
      {fields.length > 1 && (
        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
          Drag the handle to reorder fields
        </Typography>
      )}
      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={sortableIds} strategy={verticalListSortingStrategy}>
          <Stack spacing={2}>
            {fields.map((field, index) => (
              <SortableFieldCard
                key={field.clientId}
                field={field}
                index={index}
                sectionName={sectionName}
                canDelete={fields.length > 1}
                onUpdate={updateField}
                onDelete={(clientId) =>
                  setFields((prev) => prev.filter((item) => item.clientId !== clientId))
                }
              />
            ))}
          </Stack>
        </SortableContext>
      </DndContext>

      <Button
        startIcon={<Add />}
        sx={{ mt: 2 }}
        onClick={() => setFields((prev) => [...prev, newBuilderField()])}
      >
        Add Field
      </Button>
    </Box>
  )
}
