/** Turn a field label into a stable data key (e.g. "Last Login" → "lastLogin"). */
export function labelToFieldKey(label: string): string {
  const words = label
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.replace(/[^a-zA-Z0-9]/g, ''))
    .filter(Boolean)
  if (words.length === 0) return ''
  const [first, ...rest] = words
  return (
    first.charAt(0).toLowerCase() +
    first.slice(1) +
    rest.map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('')
  )
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

/** True when the id was auto-generated (empty or UUID) and can follow the label. */
export function isAutoGeneratedFieldId(id: string): boolean {
  return !id.trim() || UUID_RE.test(id)
}
